/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnchorMotionToolbar: typeof import('./components/motion/AnchorMotionToolbar.vue')['default']
    AppRouteTransition: typeof import('./components/motion/AppRouteTransition.vue')['default']
    AuthEmailInput: typeof import('./components/auth/AuthEmailInput.vue')['default']
    AuthEmailSuffixChips: typeof import('./components/auth/AuthEmailSuffixChips.vue')['default']
    BrandMark: typeof import('./components/BrandMark.vue')['default']
    ChatBrandRail: typeof import('./components/chat/ChatBrandRail.vue')['default']
    ChatQuickPromptBar: typeof import('./components/chat/ChatQuickPromptBar.vue')['default']
    ChatShareCaptureCard: typeof import('./components/chat/ChatShareCaptureCard.vue')['default']
    ChatShareDialog: typeof import('./components/chat/ChatShareDialog.vue')['default']
    ChatSidebar: typeof import('./components/chat/ChatSidebar.vue')['default']
    CodeBlock: typeof import('./components/chat/CodeBlock.vue')['default']
    DailyRecommendCard: typeof import('./components/chat/DailyRecommendCard.vue')['default']
    DailyRecommendSidebar: typeof import('./components/chat/DailyRecommendSidebar.vue')['default']
    DailyRecommendSkeleton: typeof import('./components/chat/DailyRecommendSkeleton.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    KnowledgePlanetCard: typeof import('./components/chat/KnowledgePlanetCard.vue')['default']
    KnowledgePlanetMobileEntry: typeof import('./components/chat/KnowledgePlanetMobileEntry.vue')['default']
    KnowledgePlanetMobilePage: typeof import('./components/chat/KnowledgePlanetMobilePage.vue')['default']
    KnowledgePlanetOverlay: typeof import('./components/chat/KnowledgePlanetOverlay.vue')['default']
    LocaleThemeToolbar: typeof import('./components/LocaleThemeToolbar.vue')['default']
    MarkdownRichContent: typeof import('./components/chat/MarkdownRichContent.vue')['default']
    QuickPromptChip: typeof import('./components/chat/QuickPromptChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCollapseTab: typeof import('./components/chat/SidebarCollapseTab.vue')['default']
    UserAuthDialog: typeof import('./components/UserAuthDialog.vue')['default']
  }
}
