-- 平台系统参数扩展：LOGO/附件/OCR/RAG 调优（pom 补丁 258）
INSERT IGNORE INTO sys_platform_setting (setting_key, value_text, created_at, updated_at) VALUES
('ADMIN_BRAND_LOGO_STORAGE_DIR', '', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('CHAT_ATTACHMENT_BIN_DIR', '', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('CHAT_ATTACHMENT_VISION_OCR_FALLBACK', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('DOCUMENT_LOCAL_OCR_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('DOCUMENT_LOCAL_OCR_LANGUAGES', 'chi_sim+eng', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('DOCUMENT_LOCAL_OCR_RAPID_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('DOCUMENT_LOCAL_OCR_RAPID_MODEL', 'ONNX_PPOCR_V3', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_RETRIEVAL_MODE', 'milvus_es_hybrid', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_ES_MIN_SCORE', '1.0', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
