-- 平台系统参数表 sys_platform_setting + 默认种子（pom 补丁 258）
CREATE TABLE IF NOT EXISTS sys_platform_setting (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  setting_key VARCHAR(64) NOT NULL COMMENT 'PlatformSettingKey 存储值',
  value_text MEDIUMTEXT NOT NULL COMMENT '参数值（布尔/整数/Cron 等均文本存储）',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间 UTC',
  updated_at DATETIME(3) NOT NULL COMMENT '更新时间 UTC',
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_platform_setting_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台级系统参数';

INSERT IGNORE INTO sys_platform_setting (setting_key, value_text, created_at, updated_at) VALUES
('TENANT_RUNTIME_CACHE_TTL_SECONDS', '600', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('PROMPT_TEMPLATE_CACHE_TTL_SECONDS', '600', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('LLM_USAGE_REDIS_POLL_MS', '250', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('MEMORY_ABSTRACT_REDIS_POLL_MS', '400', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('AUTH_EMAIL_CODE_TTL_SECONDS', '600', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('AUTH_EMAIL_SEND_COOLDOWN_SECONDS', '60', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('OBSERVABILITY_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('OBSERVABILITY_RETENTION_DAYS', '90', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('OBSERVABILITY_PURGE_BATCH_SIZE', '5000', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('OBSERVABILITY_QUEUE_CAPACITY', '1024', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('OBSERVABILITY_RETENTION_CRON', '0 15 4 * * *', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_QA_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_QA_JUDGE_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_QA_RETENTION_DAYS', '180', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_QA_TOP_K', '10', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_QA_RETENTION_CRON', '0 45 4 * * *', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SCHEDULED_TASKS_ENABLED', 'true', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SCHEDULED_TASKS_POLL_CRON', '0 * * * * *', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SCHEDULED_TASKS_POLLER_LOCK_TTL_SECONDS', '55', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SCHEDULED_TASKS_TASK_LOCK_TTL_SECONDS', '300', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SITE_CRAWL_LOCK_TTL_SECONDS', '21600', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
('RAG_SITE_CRAWL_QUEUE_RETENTION_CRON', '0 30 3 * * *', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
